### ISSUE TITLE
Bound platelet model

### ISSUE THREAD

**Issue by abarret** [abarret/clotting_model#46]
Below is a list of things needed to implement the full bound platelet model.

- [x] Bond formations (#47)
- [x] Bound / Activated platelet sources (#44)
- [x] Cohesion stress formation / relaxation (#45)
- [x] Wall site consumption (#49)
- [x] Implementation in main routines (#49)
- [x] Bound velocity (#42)
- [x] ~~Drag force~~ (not needed because it balances with div(sigma))
- [x] Conversion function for cohesion stress tensor (#48)

**Comment by abarret** [comment]
Wall site consumption will need to be done in the main routines. The wall sites are handled by the geometry in the application.

**Comment by abarret** [comment]
The bound model is implemented, although we've made changes to the proposed model.
